### ISSUE TITLE
Icingaweb shows nothing

### ISSUE THREAD

**Issue by Daniele6** [lippserd/docker-compose-icinga#11]
Hi,
since yesterday i can't see hosts, services and so on in icingaweb. If i run "icinga deamon -C" it confirms that there is a valid configuration. I tried to restart from zero but nothing changed.
Thank you
![nothing](https://user-images.githubusercontent.com/58933904/130770279-c25aeef0-90b6-4741-82c8-a2580c515ea4.png)
![set](https://user-images.githubusercontent.com/58933904/130770283-3aba06ea-fb21-494c-8348-25118881ffa0.png)

**Comment by 459below** [comment]
I get the same behaviour. I started testing out the docker-compose a few weeks back and it worked fine at the very start. Then after some pulling of new images it just stopped. I tried wiping the whole volumes and images, but to no avail.

Is it currently not working?

**Comment by Daniele6** [comment]
> I get the same behaviour. I started testing out the docker-compose a few weeks back and it worked fine at the very start. Then after some pulling of new images it just stopped. I tried wiping the whole volumes and images, but to no avail.
> 
> Is it currently not working?

No, it still not working. I'm trying to find a solution but i hope they will fix it

**Comment by 459below** [comment]
Please ever be so kind and try going to http://youricingaurl.com/config/modules in order to enable the module "monitoring". There is a small button with a circle of arrows.

I am new to setting up Icinga. As it may seem this stack uses a rolling release for bleeding edge images and the patch being applied on the fly while building one of the images seems to be broken.

This seems to help:

```
[root@thalamus icinga-docker-compose.old]# cat env/icingaweb2/Dockerfile 
FROM alpine/git
WORKDIR /
COPY icingadb-load-monitoring.patch .
RUN git clone https://github.com/Icinga/icingadb-web.git icingadb && \
    cd icingadb && \
    git checkout e6e5bb30d37eacaf5498f96412b4b5f400cc9309 && \
    cd .. && \
    git apply --directory icingadb icingadb-load-monitoring.patch

FROM icinga/icingaweb2:2.9
USER root
RUN rm -rf /usr/share/icingaweb2/modules/icingadb/*
USER www-data
COPY --from=0 /icingadb /usr/share/icingaweb2/modules/icingadb
```

**Comment by Daniele6** [comment]
Thank you for your reply.
It works! I did the same thing but i had to change the version of icinga/icingadb-web. if I can give you some advice, set every version because, in future, you may have the same problem with other images. 
I built a new image starting from https://github.com/Icinga/docker-icingadb and setting the version to 3f9a9aca35de245b263f7ff6123c79a6b4beb59a. Inside this repository, after cloning https://github.com/Icinga/icingadb.git as written in the "Build it yourself" section, set the version to b9ec99185a58b0294d08185a4249aa6e5c7fd71b.
Hope it may help you

**Comment by lippserd** [comment]
Hi,

Could you please try PR #13 and report if it fixes your problems?

All the best,
Eric

**Comment by 459below** [comment]
Yes! For me it does! Thank you kindly.
