### ISSUE TITLE
icingaweb not building currently?

### ISSUE THREAD

**Issue by Costly** [lippserd/docker-compose-icinga#12]
Apparently a fresh clone of this repo is not functional at the moment.

Building icingaweb
Sending build context to Docker daemon  4.608kB
Step 1/9 : FROM alpine/git
 ---> b8f176fa3f0d
Step 2/9 : WORKDIR /
 ---> Using cache
 ---> 1a6581fb2b43
Step 3/9 : COPY icingadb-load-monitoring.patch .
 ---> Using cache
 ---> d7054afe47ab
Step 4/9 : RUN git clone https://github.com/Icinga/icingadb-web.git icingadb &&     git apply --directory icingadb icingadb-load-monitoring.patch
 ---> Running in c33e4e401571
Cloning into 'icingadb'...
error: patch failed: icingadb/run.php:4
error: icingadb/run.php: patch does not apply
The command '/bin/sh -c git clone https://github.com/Icinga/icingadb-web.git icingadb &&     git apply --directory icingadb icingadb-load-monitoring.patch' returned a non-zero code: 1
ERROR: Service 'icingaweb' failed to build : Build failed

**Comment by roswitina** [comment]
same here..

**Comment by dramon889** [comment]
same here

**Comment by Daniele6** [comment]
There are problems with the patch
Try using an old version of Icinga/icingadb-web 
It works for me

**Comment by dramon889** [comment]
I've found a solution.
Use this config in the /env/icingaweb2/Dockerfile

`FROM alpine/git
WORKDIR /
COPY icingadb-load-monitoring.patch .
RUN git clone https://github.com/Icinga/icingadb-web.git icingadb && \
    cd icingadb && \
    git checkout e6e5bb30d37eacaf5498f96412b4b5f400cc9309 && \
    cd .. && \
    git apply --directory icingadb icingadb-load-monitoring.patch

FROM icinga/icingaweb2:2.9
USER root
RUN rm -rf /usr/share/icingaweb2/modules/icingadb/*
USER www-data
COPY --from=0 /icingadb /usr/share/icingaweb2/modules/icingadb`

**Comment by Costly** [comment]
> I've found a solution.
> Use this config in the /env/icingaweb2/Dockerfile
> 
> FROM alpine/git
> WORKDIR /
> COPY icingadb-load-monitoring.patch .
> RUN git clone https://github.com/Icinga/icingadb-web.git icingadb &&
> cd icingadb &&
> git checkout e6e5bb30d37eacaf5498f96412b4b5f400cc9309 &&
> cd .. &&
> git apply --directory icingadb icingadb-load-monitoring.patch
> 
> FROM icinga/icingaweb2:2.9
> USER root
> RUN rm -rf /usr/share/icingaweb2/modules/icingadb/*
> USER www-data
> COPY --from=0 /icingadb /usr/share/icingaweb2/modules/icingadb
seems there are missing some "\". Try this instead:

FROM alpine/git
WORKDIR /
COPY icingadb-load-monitoring.patch .
RUN git clone https://github.com/Icinga/icingadb-web.git icingadb && \
        cd icingadb && \
        git checkout e6e5bb30d37eacaf5498f96412b4b5f400cc9309 && \
        cd .. && \
        git apply --directory icingadb icingadb-load-monitoring.patch

FROM icinga/icingaweb2:2.9
USER root
RUN rm -rf /usr/share/icingaweb2/modules/icingadb/*
USER www-data
COPY --from=0 /icingadb /usr/share/icingaweb2/modules/icingadb

**Comment by lippserd** [comment]
Hi,

Could you please try PR #13 and report if it fixes your problems?

All the best,
Eric
