### ISSUE TITLE
How to enable the monitoring module?

### ISSUE THREAD

**Issue by ScriptJunky** [lippserd/docker-compose-icinga#14]
I've had a good bit of time working on this one, and from what I have been able to discern, the biggest issue is that the ido database for icinga2 is not present. Without monitoring, some other modules do not work. Manually installing ido-mysql breaks other parts of the icinga2 environment, so that seems like a no go as well.

Are there any docs available for getting the monitoring module functional?

**Comment by NCPSAdesso** [comment]
same here !

**Comment by djeclemen** [comment]
Looks like we are missing this step in the docker image https://icinga.com/docs/icinga-2/latest/doc/02-installation/01-Debian/#ido-with-mysql

**Comment by lippserd** [comment]
We released Icinga DB v1.0.0 today and PR #33 will update everything needed to run it. Also, all modules now have Icinga DB support.
