### ISSUE TITLE
FATAL	icingadb	redis: connection pool timeout

### ISSUE THREAD

**Issue by davidwuest** [lippserd/docker-compose-icinga#15]
2021-11-10T20:27:40.615Z	FATAL	icingadb	redis: connection pool timeout
icingadb_1         | can't perform "[xread block 0 streams icinga:stats $]"
icingadb_1         | github.com/icinga/icingadb/pkg/icingaredis.WrapCmdErr
icingadb_1         | 	/github/workspace/pkg/icingaredis/utils.go:121
icingadb_1         | github.com/icinga/icingadb/pkg/icingaredis.(*Heartbeat).controller.func1
icingadb_1         | 	/github/workspace/pkg/icingaredis/heartbeat.go:104
icingadb_1         | golang.org/x/sync/errgroup.(*Group).Go.func1
icingadb_1         | 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57
icingadb_1         | runtime.goexit
icingadb_1         | 	/usr/local/go/src/runtime/asm_amd64.s:1581
icingadb_1         | heartbeat failed
icingadb_1         | github.com/icinga/icingadb/pkg/icingaredis.(*Heartbeat).setError
icingadb_1         | 	/github/workspace/pkg/icingaredis/heartbeat.go:164
icingadb_1         | github.com/icinga/icingadb/pkg/icingaredis.(*Heartbeat).controller
icingadb_1         | 	/github/workspace/pkg/icingaredis/heartbeat.go:156
icingadb_1         | runtime.goexit
icingadb_1         | 	/usr/local/go/src/runtime/asm_amd64.s:1581
icingadb_1         | HA aborted
icingadb_1         | github.com/icinga/icingadb/pkg/icingadb.(*HA).abort.func1
icingadb_1         | 	/github/workspace/pkg/icingadb/ha.go:113
icingadb_1         | sync.(*Once).doSlow
icingadb_1         | 	/usr/local/go/src/sync/once.go:68
icingadb_1         | sync.(*Once).Do
icingadb_1         | 	/usr/local/go/src/sync/once.go:59
icingadb_1         | github.com/icinga/icingadb/pkg/icingadb.(*HA).abort
icingadb_1         | 	/github/workspace/pkg/icingadb/ha.go:111
icingadb_1         | github.com/icinga/icingadb/pkg/icingadb.(*HA).controller
icingadb_1         | 	/github/workspace/pkg/icingadb/ha.go:217
icingadb_1         | runtime.goexit
icingadb_1         | 	/usr/local/go/src/runtime/asm_amd64.s:1581
icingadb_1         | HA exited with an error
icingadb_1         | main.run
icingadb_1         | 	/github/workspace/cmd/icingadb/main.go:277
icingadb_1         | main.main
icingadb_1         | 	/github/workspace/cmd/icingadb/main.go:34
icingadb_1         | runtime.main
icingadb_1         | 	/usr/local/go/src/runtime/proc.go:255
icingadb_1         | runtime.goexit
icingadb_1         | 	/usr/local/go/src/runtime/asm_amd64.s:1581

**Comment by davidwuest** [comment]
Another try same problem. Anyone any ideas?

can't execute Redis script
icingadb_1         | github.com/icinga/icingadb/pkg/icingadb/overdue.Sync.sync
icingadb_1         | 	/github/workspace/pkg/icingadb/overdue/sync.go:190
icingadb_1         | github.com/icinga/icingadb/pkg/icingadb/overdue.Sync.Sync.func4
icingadb_1         | 	/github/workspace/pkg/icingadb/overdue/sync.go:73
icingadb_1         | golang.org/x/sync/errgroup.(*Group).Go.func1
icingadb_1         | 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57
icingadb_1         | runtime.goexit
icingadb_1         | 	/usr/local/go/src/runtime/asm_amd64.s:1581

**Comment by lippserd** [comment]
Hi,

Is your Redis image up to date? Please provide the full logs of Icinga DB and Redis and wrap them in a code block.

Please also retry with #13 since this one is going to merged soon.

All the best,
Eric

**Comment by davidwuest** [comment]
Tried with #13 
Still the same problem
`icingadb_1         | 2021-11-11T13:56:13.292Z	FATAL	icingadb	redis: connection pool timeout
icingadb_1         | can't perform "[xread block 0 streams icinga:stats $]"
icingadb_1         | github.com/icinga/icingadb/pkg/icingaredis.WrapCmdErr
icingadb_1         | 	/github/workspace/pkg/icingaredis/utils.go:121
icingadb_1         | github.com/icinga/icingadb/pkg/icingaredis.(*Heartbeat).controller.func1
icingadb_1         | 	/github/workspace/pkg/icingaredis/heartbeat.go:104
icingadb_1         | golang.org/x/sync/errgroup.(*Group).Go.func1
icingadb_1         | 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57
icingadb_1         | runtime.goexit
icingadb_1         | 	/usr/local/go/src/runtime/asm_amd64.s:1581
icingadb_1         | heartbeat failed
icingadb_1         | github.com/icinga/icingadb/pkg/icingaredis.(*Heartbeat).setError
icingadb_1         | 	/github/workspace/pkg/icingaredis/heartbeat.go:164
icingadb_1         | github.com/icinga/icingadb/pkg/icingaredis.(*Heartbeat).controller
icingadb_1         | 	/github/workspace/pkg/icingaredis/heartbeat.go:156
icingadb_1         | runtime.goexit
icingadb_1         | 	/usr/local/go/src/runtime/asm_amd64.s:1581
icingadb_1         | HA aborted
icingadb_1         | github.com/icinga/icingadb/pkg/icingadb.(*HA).abort.func1
icingadb_1         | 	/github/workspace/pkg/icingadb/ha.go:113
icingadb_1         | sync.(*Once).doSlow
icingadb_1         | 	/usr/local/go/src/sync/once.go:68
icingadb_1         | sync.(*Once).Do
icingadb_1         | 	/usr/local/go/src/sync/once.go:59
icingadb_1         | github.com/icinga/icingadb/pkg/icingadb.(*HA).abort
icingadb_1         | 	/github/workspace/pkg/icingadb/ha.go:111
icingadb_1         | github.com/icinga/icingadb/pkg/icingadb.(*HA).controller
icingadb_1         | 	/github/workspace/pkg/icingadb/ha.go:217
icingadb_1         | runtime.goexit
icingadb_1         | 	/usr/local/go/src/runtime/asm_amd64.s:1581
icingadb_1         | HA exited with an error
icingadb_1         | main.run
icingadb_1         | 	/github/workspace/cmd/icingadb/main.go:277
icingadb_1         | main.main
icingadb_1         | 	/github/workspace/cmd/icingadb/main.go:34
icingadb_1         | runtime.main
icingadb_1         | 	/usr/local/go/src/runtime/proc.go:255
icingadb_1         | runtime.goexit
icingadb_1         | 	/usr/local/go/src/runtime/asm_amd64.s:1581
icinga_icingadb_1 exited with code 1
`
