### ISSUE TITLE
best way to add (external) modules to icingaweb2?

### ISSUE THREAD

**Issue by Klar** [lippserd/docker-compose-icinga#2]
Hi,

what is in your opinion the best way to add a module to icingaweb2?

Something like: https://github.com/Mikesch-mp/icingaweb2-module-grafana

thanks.

**Comment by lippserd** [comment]
Hi @Klar,

You may add volume and mount the module to `/usr/share/icingaweb2/modules` or a custom module path which then also has to be added in the configuration.

Does this help?

All the best,
Eric

**Comment by Klar** [comment]
I added this to the 'icingaweb' entry in the docker-compose file
```
    volumes:
      - ./modules/:/usr/share/icingaweb2/modules/
```

in my (local) folder 'modules' there is the grafana plugin.

It seems that the mount is working but the grafana folder is not there, overwritten?
I also added 'grafana' to 'icingaweb.enabledModules

**Comment by fireba11** [comment]
That's a docker thing. If you mount a volume there any original content isn't accessable from the container any more.

**Comment by Klar** [comment]
Ok I found the solution:

in docker-compose.yml - icingaweb - environment:
```
      icingaweb.config.global.module_path: '/usr/share/icingaweb2/modules/:/usr/share/icingaweb2/extModules/'
```
in docker-compose.yml - icingaweb - volumes:
```
      - ./modules/:/usr/share/icingaweb2/extModules/
```

and in the directory from docker-compose.yml:
```
mkdir modules
```

add external Modules to this folder.

Thanks for the help.
