### ISSUE TITLE
possible css issue with current version

### ISSUE THREAD

**Issue by yolabingo** [lippserd/docker-compose-icinga#25]
It looks like there is a css problem, not sure if this is an icinga issue or something that can be addressed with this docker-compose example.

I pruned images and volumes, also tried this on linux and OS X.

Thanks!
<img width="1264" alt="Screen Shot 2022-02-15 at 2 54 33 PM" src="https://user-images.githubusercontent.com/628954/154156361-bd792c21-cc08-4b15-9ca8-2a409345e2b7.png">
<img width="340" alt="Screen Shot 2022-02-15 at 2 55 06 PM" src="https://user-images.githubusercontent.com/628954/154156373-abc671a4-450a-4181-890f-121e49c32881.png">

**Comment by hadoken79** [comment]
Same here. 
CSS and JS download works
![image](https://user-images.githubusercontent.com/52121991/154274944-bbab66d0-0497-43d2-ae36-1e117872b668.png)
console errors:
![image](https://user-images.githubusercontent.com/52121991/154275084-d5a1cc07-661b-4114-a040-863df84e7696.png)
But no styling
![image](https://user-images.githubusercontent.com/52121991/154275306-24fd078b-d51f-461f-bd04-cf11a5b93083.png)

**Comment by davidzach** [comment]
Hello,

The problem can possibly be fixed by using only stable images.

Replace: image: icinga/icinga2
By: image: icinga/icinga2:latest

Replace: FROM icinga/icingaweb2
By: FROM icinga/icingaweb2:latest

After that, a 'docker-compose build' should apply the correct images.

Please let me know if this works.

**Comment by hadoken79** [comment]
> 

That helped, thank you.

**Comment by dcw312** [comment]
The above didn't fix it for me. Still shows like the original post screen shot. It would be helpful if the README recommended pulling a specific versioned tag that works. I spent 20 minutes trying to make this work, maybe I'll try to make it work more later.

**Comment by oy1** [comment]
Grabbing latest images till fixes the CSS issue. I've changed all images to `:latest` in the `docker-compose` file and `Dockerfile`.

**Comment by oy1** [comment]
@agustt 
Try deleting line 23 `COPY --from=0 /Legacy.less /usr/share/icingaweb2/public/css/themes/Legacy.less` in file `docker-compose-icinga/env/icingaweb2/Dockerfile`. Afther that make sure to rebuild icingaweb2 image.
