### ISSUE TITLE
It seems that Icinga DB is not running. Make sure Icinga DB is running and writing into the database.

### ISSUE THREAD

**Issue by lucamoli84** [lippserd/docker-compose-icinga#26]
Hi,

I just spun up the docker-compose.yml with the corrections indicated [https://github.com/lippserd/docker-compose-icinga/issues/25](url) but I get the following:

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/70350654/156883240-c8949e41-5f1c-4358-8ffc-ed03c586d0f5.png">

`icinga_init-icinga2_1 exited with code 127
icingaweb-mysql_1  | 2022-03-05T12:19:37.418094Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
icingadb-mysql_1   | 2022-03-05T12:19:37.664320Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
icinga_icingaweb_1 exited with code 1
icingaweb_1        | [Sat Mar 5 12:19:38.724614052 2022] [docker_entrypoint:debug] [pid 1] DOCKERE: Checking database resource "icingaweb-mysql"
icingaweb_1        | ERROR: PDOException in /usr/share/icingaweb2/modules/setup/library/Setup/Utils/DbTool.php:352 with message: SQLSTATE[HY000] [2002] Connection refused
icingaweb_1        | [Sat Mar 5 12:19:38.761521993 2022] [docker_entrypoint:crit] [pid 1] DOCKERE: exit status 1
icingaweb_1        | [Sat Mar 5 12:19:39.722666858 2022] [docker_entrypoint:debug] [pid 1] DOCKERE: Checking database resource "icingaweb-mysql"
icingaweb_1        | ERROR: PDOException in /usr/share/icingaweb2/modules/setup/library/Setup/Utils/DbTool.php:352 with message: SQLSTATE[HY000] [2002] Connection refused
icingaweb_1        | [Sat Mar 5 12:19:39.75976703 2022] [docker_entrypoint:crit] [pid 1] DOCKERE: exit status 1
icinga_icingaweb_1 exited with code 1
icingaweb_1        | [Sat Mar 5 12:19:41.050324806 2022] [docker_entrypoint:debug] [pid 1] DOCKERE: Checking database resource "icingaweb-mysql"
icingaweb_1        | ERROR: PDOException in /usr/share/icingaweb2/modules/setup/library/Setup/Utils/DbTool.php:352 with message: SQLSTATE[HY000] [2002] Connection refused
icingaweb_1        | [Sat Mar 5 12:19:41.086066293 2022] [docker_entrypoint:crit] [pid 1] DOCKERE: exit status 1
icingaweb-mysql_1  | 2022-03-05 12:19:41+00:00 [Note] [Entrypoint]: Database files initialized
icingaweb-mysql_1  | 2022-03-05 12:19:41+00:00 [Note] [Entrypoint]: Starting temporary server
icingaweb-mysql_1  | 2022-03-05T12:19:41.294738Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.21) starting as process 92
icingaweb-mysql_1  | 2022-03-05T12:19:41.306023Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
icingadb-mysql_1   | 2022-03-05 12:19:41+00:00 [Note] [Entrypoint]: Database files initialized
icingadb-mysql_1   | 2022-03-05 12:19:41+00:00 [Note] [Entrypoint]: Starting temporary server
icingaweb-mysql_1  | 2022-03-05T12:19:41.481170Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
icingaweb-mysql_1  | 2022-03-05T12:19:41.564054Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
icinga_icingaweb_1 exited with code 1
icingadb-mysql_1   | 2022-03-05T12:19:41.631818Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.21) starting as process 92
icingadb-mysql_1   | 2022-03-05T12:19:41.642068Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
icingaweb-mysql_1  | 2022-03-05T12:19:41.697917Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
icingaweb-mysql_1  | 2022-03-05T12:19:41.698058Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
icingaweb-mysql_1  | 2022-03-05T12:19:41.700581Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
icingaweb-mysql_1  | 2022-03-05T12:19:41.714704Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.21'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
icingaweb-mysql_1  | 2022-03-05 12:19:41+00:00 [Note] [Entrypoint]: Temporary server started.
icingadb-mysql_1   | 2022-03-05T12:19:41.853311Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
icingadb-mysql_1   | 2022-03-05T12:19:41.935287Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
icingadb-mysql_1   | 2022-03-05T12:19:42.072814Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
icingadb-mysql_1   | 2022-03-05T12:19:42.072954Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
icingadb-mysql_1   | 2022-03-05T12:19:42.076203Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
icingadb-mysql_1   | 2022-03-05T12:19:42.088154Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.21'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.`

can anyone help me out? 

Thx.

**Comment by matiaskusack** [comment]
Same here.

**Comment by matiaskusack** [comment]
Ok, found it: #30 

This solved my problem.
