### ISSUE TITLE
docker compose fails due to php requirement

### ISSUE THREAD

**Issue by maciejbrylewicz** [lippserd/docker-compose-icinga#32]
Hi, docker compose fails with the following error:

#0 14.68 Your requirements could not be resolved to an installable set of packages.
#0 14.68 
#0 14.68   Problem 1
#0 14.68     - Root composer.json requires php 7.2.34 but your php version (7.4.28; overridden via config.platform, same as actual) does not satisfy that requirement.
#0 14.68 
#0 14.68 
#0 14.68 Installation failed, reverting ./composer.json and ./composer.lock to their original content.
------
failed to solve: executor failed running [/bin/sh -c apt update     && apt install -y composer      && composer config  -d /usr/share/icinga-php/ipl platform.php $(php -r 'echo PHP_VERSION;')     && composer require -d /usr/share/icinga-php/ipl ipl/stdlib:dev-master     && composer require -d /usr/share/icinga-php/ipl ipl/html:dev-master     && composer require -d /usr/share/icinga-php/ipl ipl/orm:dev-master     && composer require -d /usr/share/icinga-php/ipl ipl/sql:dev-master     && composer require -d /usr/share/icinga-php/ipl ipl/validator:dev-master     && composer require -d /usr/share/icinga-php/ipl ipl/web:dev-master     && composer update -d /usr/share/icinga-php/ipl]: exit code: 2

Anybody solved this one or has a workaround?

**Comment by Mordecaine** [comment]
Adding this line
````
RUN apt update \
    && apt install -y composer \
    && composer config -d /usr/share/icinga-php/ipl platform.php $(php -r 'echo PHP_VERSION;') \
+   && composer require -d /usr/share/icinga-php/ipl php $(php -r 'echo PHP_VERSION;') \
    && composer require -d /usr/share/icinga-php/ipl ipl/stdlib:dev-master \
    && composer require -d /usr/share/icinga-php/ipl ipl/html:dev-master \

````
to 
`env/icingaweb2/Dockerfile`

Fixed the problem for me
