### ISSUE TITLE
How to add Icinga Director ?

### ISSUE THREAD

**Issue by tasism** [lippserd/docker-compose-icinga#4]
Hi, to make the docker-compose fully usable it would be great if Icinga Director were also included.

What would be the better day for doing this ? Because it is not just adding a volume but also creating a db user, the corresponding db schema, enable the API connection, etc.

Thank you in advance if you find time to include this!

**Comment by stefanjay** [comment]
Hey there, I know that's pretty old but can be solved quickly - just in the icinga2 frontend click on `Configuration > Modules > enable reactbundle, incubator > enable director > setup connection to the DB and the icinga2 endpoint`

I hope that was clearing it up a bit.

**Comment by lippserd** [comment]
We are now installing Icinga Web 2.9 and Icinga Director 1.8.1, which is also activated by default. Without the daemon, but that shouldn't be a problem. You have to select `icingadb-web` as the Director resource, let Director create the schema and then run the kickstart against `icinga2` with the API user `icingaweb`:`icingaweb` and you're good to go.
