### ISSUE TITLE
Declaration of ipl\Web\Compat\CompatController::setAutorefreshInterval($interval) should be compatible with Icinga\Web\Controller\ActionController::setAutorefreshInterval($interval, $bypassUserPreferences = false)

### ISSUE THREAD

**Issue by claenjoy** [lippserd/docker-compose-icinga#7]
![image](https://user-images.githubusercontent.com/2983049/103291614-147c6580-49e4-11eb-8f63-2b57552a2183.png)

![image](https://user-images.githubusercontent.com/2983049/103291637-1fcf9100-49e4-11eb-8092-28065961205e.png)

**Comment by lindi200000** [comment]
Hey, i have the same Error

**Comment by daFritz84** [comment]
same for me, seems like some issue with the latest docker image.

Luckely, there is also an older version of the image tagged. Replace ```icinga/icingaweb2:master``` with ```icinga/icingaweb2:database-configuration-backend-3770``` and it works. Alas this is not a permanent fix, but it very well serve as a workaround for now.

**Comment by claenjoy** [comment]
worked ! thanks !
