### ISSUE TITLE
Error: Class 'ipl\\I18n\\GettextTranslator' not found

### ISSUE THREAD

**Issue by dirkreitz** [lippserd/docker-compose-icinga#9]
The container icinga/icingaweb2 is constantly restarting ...

{"log":"PHP Fatal error: Uncaught Error: Class 'ipl\I18n\GettextTranslator' not found in /usr/share/icingaweb2/library/Icinga/Application/ApplicationBootst
rap.php:710\n","stream":"stderr","time":"2021-06-08T11:32:06.940588098Z"}
{"log":"Stack trace:\n","stream":"stderr","time":"2021-06-08T11:32:06.9406087Z"}
{"log":"#0 /usr/share/icingaweb2/library/Icinga/Application/Cli.php(44): Icinga\Application\ApplicationBootstrap-\u003eprepareInternationalization()\n","str
eam":"stderr","time":"2021-06-08T11:32:06.940612701Z"}
{"log":"#1 /usr/share/icingaweb2/library/Icinga/Application/ApplicationBootstrap.php(416): Icinga\Application\Cli-\u003ebootstrap()\n","stream":"stderr","ti
me":"2021-06-08T11:32:06.940617201Z"}
{"log":"#2 /usr/share/icingaweb2/bin/icingacli(7): Icinga\Application\ApplicationBootstrap::start()\n","stream":"stderr","time":"2021-06-08T11:32:06.9406278
03Z"}
{"log":"#3 {main}\n","stream":"stderr","time":"2021-06-08T11:32:06.940632503Z"}
{"log":" thrown in /usr/share/icingaweb2/library/Icinga/Application/ApplicationBootstrap.php on line 710\n","stream":"stderr","time":"2021-06-08T11:32:06.940
635703Z"}
{"log":"[Tue Jun 8 11:32:06.945395132 2021] [docker_entrypoint:crit] [pid 1] DOCKERE: exit status 255\n","stream":"stderr","time":"2021-06-08T11:32:06.9454925
43Z"}

Docker version 20.10.7, build f0df350 on Ubuntu 20.04-LTS running your docker-compose.yml file

has been filed as issue#41 (https://github.com/Icinga/docker-icingaweb2/issues/41)

solution: change image from 'icinga/icingaweb2:master' to 'icinga/icingaweb2:latest'

**Comment by lippserd** [comment]
Should be fixed now. If you still have any problems, please open a new issue.
